kind: Pod
apiVersion: v1
metadata:
 name: multipod1
spec:
 containers:
  - name: mcp1
    image: httpd
    ports:
    - containerPort: 80
  - name: mcp3
    image: httpd
    ports:
    - containerPort: 8080
  - name: mcp2
    image: ubuntu
    command: ["/bin/bash", "-c","while true; do echo hello world; sleep 300; done"]